// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdswHoprtmhCyYrMk3aVIji6PTMI0p4eU',
    appId: '1:997491972161:web:c62585a73d254ea07ecec0',
    messagingSenderId: '997491972161',
    projectId: 'wohnapp-mvp',
    authDomain: 'wohnapp-mvp.firebaseapp.com',
    storageBucket: 'wohnapp-mvp.firebasestorage.app',
    measurementId: 'G-4R6SG1C03P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7061rUWQuVXNBM43jmNCifX3xVXmVK68',
    appId: '1:997491972161:android:6c1c0af52a5b4f9b7ecec0',
    messagingSenderId: '997491972161',
    projectId: 'wohnapp-mvp',
    storageBucket: 'wohnapp-mvp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoR665yP_VgaHiNKlmf6GHfholxzqaaMA',
    appId: '1:997491972161:ios:c1bd856064e4b4097ecec0',
    messagingSenderId: '997491972161',
    projectId: 'wohnapp-mvp',
    storageBucket: 'wohnapp-mvp.firebasestorage.app',
    iosBundleId: 'com.example.wohnapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBoR665yP_VgaHiNKlmf6GHfholxzqaaMA',
    appId: '1:997491972161:ios:c1bd856064e4b4097ecec0',
    messagingSenderId: '997491972161',
    projectId: 'wohnapp-mvp',
    storageBucket: 'wohnapp-mvp.firebasestorage.app',
    iosBundleId: 'com.example.wohnapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdswHoprtmhCyYrMk3aVIji6PTMI0p4eU',
    appId: '1:997491972161:web:64feb8532ecc06eb7ecec0',
    messagingSenderId: '997491972161',
    projectId: 'wohnapp-mvp',
    authDomain: 'wohnapp-mvp.firebaseapp.com',
    storageBucket: 'wohnapp-mvp.firebasestorage.app',
    measurementId: 'G-16DT9BSJJ3',
  );
}
